// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    name, username, email, img, description
) VALUES (
             $1, $2, $3, $4, $5
         )
RETURNING id, name, username, email, img, since, description
`

type CreateUserParams struct {
	Name        string
	Username    string
	Email       string
	Img         pgtype.Text
	Description pgtype.Text
}

// -- name: ListServers :many
// SELECT * FROM servers
// WHERE;
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Img,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Img,
		&i.Since,
		&i.Description,
	)
	return i, err
}
