// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserOrDoNothing = `-- name: CreateUserOrDoNothing :exec


INSERT INTO users (name, username, email, img, description, provider)
VALUES ($1, $2, $3, $4, $5, $6)
    ON CONFLICT (email) DO NOTHING
`

type CreateUserOrDoNothingParams struct {
	Name        string
	Username    string
	Email       string
	Img         pgtype.Text
	Description pgtype.Text
	Provider    AuthType
}

// -- name: ListServers :many
// SELECT * FROM servers
// WHERE;
// -- name: CreateUser :one
// INSERT INTO users (
//
//	name, username, email, img, description
//
// ) VALUES (
//
//	    $1, $2, $3, $4, $5
//	)
//
// RETURNING *;
func (q *Queries) CreateUserOrDoNothing(ctx context.Context, arg CreateUserOrDoNothingParams) error {
	_, err := q.db.Exec(ctx, createUserOrDoNothing,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Img,
		arg.Description,
		arg.Provider,
	)
	return err
}
